version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=roaa
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=ticket_system
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: